[project]
name = "bayesian-neural-networks"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Dmitriy Basov", email = "dimabasow@vk.com" }
]
requires-python = ">=3.9"
dependencies = [
    "polars>=1.27.1",
    "scipy>=1.13.1",
]

[project.optional-dependencies]
cpu = [
  "torch>=2.6.0",
]
cu126 = [
  "torch>=2.6.0",
  "pytorch-triton",
]
cu128 = [
  "torch>=2.6.0",
  "pytorch-triton",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu126" },
    { extra = "cu128" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu126", extra = "cu126" },
  { index = "pytorch-cu128-nightly", extra = "cu128" },
]
pytorch-triton = [
  { index = "pytorch-cu126", extra = "cu126" },
  { index = "pytorch-cu128-nightly", extra = "cu128" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128-nightly"
url = "https://download.pytorch.org/whl/nightly/cu128"
explicit = true
